import { methodId, type MethodId } from "../domain/ids.js";
import type {
  MethodContractMetadata,
  MethodScientificConfidence,
  RecommendationEligibility,
} from "./methodSpecificationRegistry.js";
import { cloneAndDeepFreeze } from "./immutableRegistry.js";

type ContractReferenceFields = Pick<
  MethodContractMetadata,
  | "contractEquationRef"
  | "contractApplicabilityRef"
  | "contractWarningRef"
  | "contractValidationRef"
>;

type ContractMetadataInput = Omit<
  MethodContractMetadata,
  keyof ContractReferenceFields
>;

function contractReferences(id: MethodId): ContractReferenceFields {
  const base = `CALCULATION_CONTRACTS.md#${id}`;
  return {
    contractEquationRef: `${base}:Equation`,
    contractApplicabilityRef: `${base}:Applicability`,
    contractWarningRef: `${base}:Warning predicates`,
    contractValidationRef: `${base}:Validation`,
  };
}

function contractMetadata(
  id: string,
  input: ContractMetadataInput,
): readonly [MethodId, MethodContractMetadata] {
  const controlledId = methodId(id);
  return [
    controlledId,
    {
      ...input,
      ...contractReferences(controlledId),
    },
  ];
}

function confidence(
  scientificConfidence: MethodScientificConfidence | null,
  scientificConfidenceRaw: string,
  confidenceResolutionReason: string,
): Pick<
  MethodContractMetadata,
  | "scientificConfidence"
  | "scientificConfidenceRaw"
  | "confidenceResolutionReason"
> {
  return {
    scientificConfidence,
    scientificConfidenceRaw,
    confidenceResolutionReason,
  };
}

function recommendation(
  recommendationEligibility: RecommendationEligibility,
  recommendationReason: string,
): Pick<
  MethodContractMetadata,
  "recommendationEligibility" | "recommendationReason"
> {
  return { recommendationEligibility, recommendationReason };
}

const NO_EXPLICIT_RECOMMENDATION = recommendation(
  null,
  "No explicit Recommended policy for this top-level method is frozen in the four source files.",
);

const ENTRIES = [
  contractMetadata("A-01", {
    inputParameterIds: [
      "material_id",
      "property_id",
      "state.temperature",
      "state.frequency/field/pressure/...",
      "interpolation_id",
    ],
    outputQuantityIds: ["property_snapshot"],
    applicabilityDomain:
      "Only inside the selected material/state dataset envelope with sufficient independent variables; no unaudited smoothing across Curie, phase, or dataset segments.",
    warningPredicates: [
      "outside_domain -> insufficient_data",
      "required H/f/p is missing",
      "phase boundary is crossed",
      "material state or grade does not match",
      "dataset contains a nonphysical negative value",
      "dataset version is not approved",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["MAT-P-001", "MAT-P-002"],
    validationNotes:
      "MAT-P-001 specified with TOL-PROP; MAT-P-002 specified. The first production dataset is not yet established.",
    sourceRefs: ["ID-DATA-01", "DER-ENERGY", "per-property source record"],
    ...confidence(
      "high",
      "A (only inside the original data envelope; each material datum is reviewed separately)",
      "A maps to high; the qualification remains part of the applicability domain.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("A-02", {
    inputParameterIds: [
      "water.temperature",
      "water.pressure_abs",
      "phase_requirement",
    ],
    outputQuantityIds: ["rho", "cp", "mu", "k", "h", "Tsat", "region/status"],
    applicabilityDomain:
      "Known absolute pressure and single-phase water inside the selected release; mixtures and glycol are not applicable. SR6-08 is a separate strict-domain simplification near 0.1 MPa.",
    warningPredicates: [
      "absolute pressure is unknown",
      "two-phase state or selected-release domain exceeded",
      "state approaches saturation",
      "explicit constant-property approximation exceeds its declared window",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["MAT-W-001", "MAT-W-002"],
    validationNotes:
      "MAT-W-001 and MAT-W-002 are blocked because the implementation/version is not selected; an enabled SR6 child also requires a full-model difference check.",
    sourceRefs: [
      "IAPWS-95 or IAPWS-IF97",
      "IAPWS-R12-08",
      "IAPWS-R15-11",
      "IAPWS-SR6-08(2011):optional-strict-domain",
      "local copies and implementation hashes missing",
    ],
    ...confidence(
      null,
      "C/VFY (method sources separated; local versions, implementation and official-node regressions are not frozen)",
      "C/VFY is a composite audit summary and cannot be normalized to one machine value before child-method splitting.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("B-01", {
    inputParameterIds: [
      "coil.electrical_turn_count",
      "coil.turn_center_z[]",
      "coil.helix_revolution_count",
      "coil.helix_axial_advance",
      "coil.inner_diameter",
      "coil.outer_diameter",
      "coil.mean_diameter",
      "coil.current_path_diameter",
      "conductor.radial_size",
      "conductor.axial_size",
      "coil.pitch_center",
      "coil.lead_length",
    ],
    outputQuantityIds: [
      "D_i",
      "D_o",
      "D_m",
      "D_c",
      "d_rad",
      "d_ax",
      "p",
      "g",
      "b_cc",
      "b_env",
      "N",
      "N_rev",
      "delta_z_helix",
      "lead_length",
      "z_i",
      "dimensionless ratios with explicit denominators",
    ],
    applicabilityDomain:
      "Cylindrical axis and section directions are explicit and all measurement datums are consistent.",
    warningPredicates: [
      "N=1 is routed to a current-sheet method requiring b>0",
      "Np is treated as axial length",
      "geometry-identity residual exceeds input uncertainty",
      "g<0",
      "multilayer winding is labelled single-layer",
      "effective current centroid is unknown",
    ],
    warningIds: [],
    validationCaseIds: ["GEO-001", "GEO-002"],
    methodCheckIds: [],
    validationNotes: "GEO-001 and GEO-002 are central cases with status specified.",
    sourceRefs: ["ID-GEO-01", "ADR-0003", "DER-GEO", "ENGINEERING_PARAMETER_DICTIONARY"],
    ...confidence(
      "high",
      "A (after the geometry definition was approved); historical workbook chain X",
      "The approved project definition maps from A to high; X applies only to the rejected historical workbook chain.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("B-02", {
    inputParameterIds: [
      "coil.electrical_turn_count",
      "conductor.axial_size",
      "coil.winding_envelope_length",
    ],
    outputQuantityIds: ["k_fill_axial"],
    applicabilityDomain:
      "Uniform, identical, non-overlapping single-layer turns; inclined or unusual sections are only a projected-coverage definition.",
    warningPredicates: [
      "k_fill_axial>1 -> invalid_input",
      "b_env is not defined by ADR-0003",
      "mixed sections or multilayer geometry is passed directly",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["GEO-FILL-001"],
    validationNotes: "GEO-FILL-001 executed_pass.",
    sourceRefs: ["ID-GEO-01", "ADR-0003", "DER-GEO"],
    ...confidence(
      "high",
      "A (approved geometry definition); not an electromagnetic coupling coefficient",
      "A maps to high for the approved definition.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("B-03", {
    inputParameterIds: [
      "coil.current_path_diameter",
      "coil.winding_envelope_length",
      "coil.electrical_turn_count",
      "core.relative_permeability",
    ],
    outputQuantityIds: ["L_inf"],
    applicabilityDomain:
      "Infinite-length uniform current sheet with a uniform linear core; a limiting comparison only, not a normal finite-coil result.",
    warningPredicates: [
      "b=0",
      "N=1 and b_cc=0",
      "finite-length result is presented as the primary result",
      "ferromagnetic nonlinearity is present",
    ],
    warningIds: [],
    validationCaseIds: ["EM-L-001"],
    methodCheckIds: ["EM-L-LONG-SCALE-001"],
    validationNotes: "EM-L-001 central case specified; EM-L-LONG-SCALE-001 specified with TOL-ID.",
    sourceRefs: ["N09:PDF20-21:eq15-18", "RG12:PDF116-135", "ID-EM-01", "DER-EM"],
    ...confidence(
      "high",
      "A (long-solenoid limit only)",
      "A maps to high inside the stated analytical limit.",
    ),
    ...recommendation("not_eligible", "C-01 freezes B-03 as a long-coil limit check only."),
  }),
  contractMetadata("B-04", {
    inputParameterIds: [
      "coil.current_path_diameter",
      "coil.winding_envelope_length",
      "coil.electrical_turn_count",
    ],
    outputQuantityIds: ["L_sheet", "K_N"],
    applicabilityDomain:
      "Uniform infinitely thin cylindrical surface ampere-turns; excludes pitch, leads, finite section, proximity, workpiece and distributed capacitance.",
    warningPredicates: [
      "few turns, large pitch, or thick conductor",
      "mean current path is uncertain",
      "branch disagreement exceeds the paper approximation error",
      "K_N is multiplied a second time",
    ],
    warningIds: [],
    validationCaseIds: ["EM-L-003", "EM-L-006", "EM-L-001"],
    methodCheckIds: ["EM-L-BRANCH-001"],
    validationNotes:
      "EM-L-003 executed_pass with source_review_status=pending_release_cross_check; EM-L-006 and EM-L-001 specified; EM-L-BRANCH-001 executed_pass.",
    sourceRefs: [
      "L85:PDF3-4:PRINT1428-1429:eq9-12:table1",
      "N09:PDF20-21:PRINT19-20:eq15-18",
      "N09:PDF32-34:tables",
      "CODATA22",
    ],
    ...confidence(
      "high",
      "A (cylindrical current sheet; six-digit fit accuracy is not physical-coil accuracy)",
      "A maps to high inside the current-sheet model domain.",
    ),
    ...recommendation(
      "conditionally_eligible",
      "C-01 recommends B-04 only for an air-core uniform single-layer winding satisfying the cylindrical current-sheet assumptions.",
    ),
  }),
  contractMetadata("B-05", {
    inputParameterIds: [
      "coil.current_path_diameter",
      "coil.winding_envelope_length",
      "coil.electrical_turn_count",
    ],
    outputQuantityIds: ["L_Wheeler"],
    applicabilityDomain:
      "Wheeler's original single-layer geometry; the approximately 1% statement applies only for b>0.8a and is not a hard model switch.",
    warningPredicates: [
      "diameter is passed to a radius formula",
      "millimetres are passed directly to the inch formula",
      "b<=0.8a",
      "few turns, large pitch, or thick conductor",
      "a Nagaoka factor is applied again",
    ],
    warningIds: [],
    validationCaseIds: ["EM-L-002", "EM-L-006"],
    methodCheckIds: ["EM-L-W28-DOMAIN-001"],
    validationNotes: "Both central cases and the method-domain check are specified.",
    sourceRefs: ["W28:PDF2:PRINT1399:eq2", "W28:PDF3:PRINT1400:eq3"],
    ...confidence(
      "engineering_approximation",
      "C (engineering approximation; eq.2 1% statement only for b>0.8a)",
      "C maps to engineering_approximation.",
    ),
    ...recommendation("not_eligible", "C-01 freezes B-05 as an in-domain quick comparison only."),
  }),
  contractMetadata("B-06", {
    inputParameterIds: [
      "coil.multilayer_mean_radius",
      "coil.multilayer_axial_length",
      "coil.multilayer_radial_build",
      "coil.electrical_turn_count",
      "coil.layer_count",
    ],
    outputQuantityIds: ["L_Wheeler_multilayer"],
    applicabilityDomain:
      "Genuine approximately uniform multilayer winding resembling Wheeler Fig. 1; the approximately 1% statement additionally requires the three denominator terms to be comparable.",
    warningPredicates: [
      "N_layer<2 -> not_applicable",
      "single-conductor radial size is used as c_ml",
      "single-layer D_c is used as a_ml",
      "layer radii or turn distribution is strongly nonuniform",
      "approximately 1% is claimed outside the stated shape condition",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["EM-L-ML-001"],
    validationNotes: "EM-L-ML-001 specified with TOL-ID.",
    sourceRefs: ["W28:PDF1:PRINT1398:Fig1:eq1"],
    ...confidence(
      "engineering_approximation",
      "C (verified primary page; genuine uniform multilayer engineering approximation with restricted 1% statement)",
      "C maps to engineering_approximation.",
    ),
    ...recommendation(
      null,
      "C-01 only states that B-06 uses an independent multilayer route and does not participate in the single-layer recommendation policy.",
    ),
  }),
  contractMetadata("B-07", {
    inputParameterIds: [
      "turn.radius[]",
      "turn.axial_position[]",
      "conductor.round_radius",
      "current_distribution",
    ],
    outputQuantityIds: ["L_total", "Lself_i", "Mij"],
    applicabilityDomain:
      "Each turn is a planar coaxial loop; the current self-inductance approximation excludes hollow thick tube, rectangular tube, strong skin effect and a real continuous helix.",
    warningPredicates: [
      "i=j mutual-inductance singularity",
      "r_c/a is not small",
      "turns intersect",
      "hollow or rectangular section uses the -7/4 self term",
      "lead contribution is missing",
    ],
    warningIds: [],
    validationCaseIds: ["EM-L-005", "EM-L-006", "EM-L-004"],
    methodCheckIds: [],
    validationNotes: "EM-L-005 and EM-L-006 specified; EM-L-004 blocked pending signed CGS-to-SI chain.",
    sourceRefs: ["RG12:PDF6:eq1", "RG12:PDF123:eq81", "RG12:PDF126-128:Example57", "DER-EM:SI-normalization-pending"],
    ...confidence(
      null,
      "A/C (filament mutual inductance A; finite-section single-turn approximation C only for thin solid round wire)",
      "The composite A/C audit summary must be split into child methods before assigning one machine confidence.",
    ),
    ...recommendation(
      "conditionally_eligible",
      "C-01 permits B-07 only when coaxial planar-ring geometry, complete turn positions/radii, supported thin solid round section and current-distribution assumptions all hold and omitted helix/lead/proximity effects are insignificant.",
    ),
  }),
  contractMetadata("B-08", {
    inputParameterIds: ["integrand_id", "limits", "segment_count"],
    outputQuantityIds: ["integral value", "refinement difference", "function evaluation count"],
    applicabilityDomain:
      "The integrand satisfies Simpson smoothness requirements; near an elliptic-integral endpoint singularity, a transformation or authoritative library is required.",
    warningPredicates: [
      "segment_count is odd",
      "endpoint is singular",
      "only one grid is evaluated",
      "numerical convergence is described as physical accuracy",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["NUM-SIMP-001", "NUM-SIMP-002"],
    validationNotes: "NUM-SIMP-001 and NUM-SIMP-002 specified.",
    sourceRefs: ["ID-NUM-01", "standard composite Simpson derivation", "textbook page missing"],
    ...confidence(
      "engineering_approximation",
      "C (numerical checker, not a physical model)",
      "C maps to engineering_approximation without upgrading the checked physical model.",
    ),
    ...recommendation("not_eligible", "The basis explicitly says B-08 is a numerical checker, not an inductance physical model."),
  }),
  contractMetadata("C-01", {
    inputParameterIds: ["normalized_geometry", "method_ids[]", "reference_result"],
    outputQuantityIds: [
      "per-method L/status/domain/source",
      "delta_L",
      "relative_difference",
      "spread",
      "recommended_method_id",
      "recommended_reason",
    ],
    applicabilityDomain:
      "All methods consume exactly the same frozen geometry, properties, units and mappings; external references are independent validation only.",
    warningPredicates: [
      "input mappings differ",
      "reference result participated in fitting",
      "N, pitch ratio, or method-difference percentage is treated as an unapproved hard switch",
      "agreement between methods is described as validation",
      "B-04 and B-07 are both ineligible while limited comparison results remain displayable",
    ],
    warningIds: ["no_approved_recommended_result"],
    validationCaseIds: ["EM-L-006"],
    methodCheckIds: ["CMP-001"],
    validationNotes: "EM-L-006 central case specified; CMP-001 specified.",
    sourceRefs: ["ID-QA-01", "VALIDATION_CASES.md", "DER-EM"],
    ...confidence(
      "high",
      "A (compare each method only inside its frozen domain; no unsupported universal thresholds)",
      "A maps to high for the comparison contract itself.",
    ),
    ...recommendation(
      null,
      "C-01 is the recommendation router, not a candidate result method; it returns a B-04/B-07 recommendation or null under its frozen policy.",
    ),
  }),
  contractMetadata("D-01", {
    inputParameterIds: [
      "coil.mean_diameter",
      "coil.helix_revolution_count",
      "coil.helix_axial_advance",
      "lead/bus.segment_lengths[]",
    ],
    outputQuantityIds: ["ell_helix", "ell_lead", "ell_bus", "ell_total"],
    applicabilityDomain:
      "Uniform cylindrical helix; noncircular or multilayer paths require segmentwise 3D CAD centerline integration.",
    warningPredicates: [
      "N_rev is guessed from N",
      "D_c is used as the mechanical path diameter",
      "lead length is unknown",
      "delta_z_helix conflicts with the turn-center span",
      "multilayer or unusual geometry uses the one-segment helix method",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["GEO-LEN-001"],
    validationNotes:
      "GEO-LEN-001 specified with TOL-ID; the delta_z_helix -> 0 limiting check is specified but has no separate method_check_id.",
    sourceRefs: ["ID-GEO-02", "DER-GEO"],
    ...confidence(
      "high",
      "A (mechanical/CAD center path, not D_c; endpoint convention must be explicit)",
      "A maps to high inside the stated geometry convention.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("D-02", {
    inputParameterIds: ["conductor.shape", "outer_dimensions", "inner_dimensions"],
    outputQuantityIds: ["Ametal", "Ahydraulic", "Pwetted", "Dh"],
    applicabilityDomain:
      "Ideal constant section; significant corners, eccentricity or deposits require actual CAD section properties.",
    warningPredicates: [
      "inner dimension is not smaller than outer dimension",
      "Ahydraulic is used as Ametal",
      "off-center wall geometry uses a centered-hole formula",
      "unknown corner radii are significant",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["GEO-AREA-001"],
    validationNotes: "GEO-AREA-001 specified with TOL-ID.",
    sourceRefs: ["ID-GEO-03", "DER-GEO"],
    ...confidence("high", "A", "A maps to high."),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("D-03", {
    inputParameterIds: [
      "conductor.length",
      "conductor.metal_area",
      "material.resistivity_snapshot",
      "series_extra_resistances[]",
    ],
    outputQuantityIds: ["Rconductor_dc", "Rterminal_dc"],
    applicabilityDomain:
      "Uniform material, section and temperature for the closed form; nonuniform cases require a separately registered segmentwise numerical method. Extra resistances are series terms.",
    warningPredicates: [
      "20 C resistivity is used for a hot conductor",
      "joint resistance is unknown",
      "joint resistance is included both geometrically and as a measured extra",
      "section varies along the path",
    ],
    warningIds: [],
    validationCaseIds: ["ELEC-RDC-001"],
    methodCheckIds: ["ELEC-RDC-MEAS-001"],
    validationNotes: "ELEC-RDC-001 central case specified; ELEC-RDC-MEAS-001 blocked.",
    sourceRefs: ["ID-OHM-01", "DER-CIRCUIT", "material source required separately"],
    ...confidence("high", "A", "A maps to high."),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("D-04", {
    inputParameterIds: [
      "frequency",
      "copper.resistivity_snapshot",
      "copper.relative_permeability",
    ],
    outputQuantityIds: ["delta_Cu"],
    applicabilityDomain:
      "Linear homogeneous good conductor in sinusoidal steady state under the local-plane approximation; not a thermal penetration depth.",
    warningPredicates: [
      "f<=0",
      "resistivity appears to be ohm-centimetres without conversion",
      "cold resistivity is used for hot copper",
      "skin depth is called thermal penetration depth",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["EM-S-001", "EM-S-002"],
    validationNotes: "EM-S-001 and EM-S-002 executed_pass with TOL-ID.",
    sourceRefs: ["ID-EM-01", "JM95:PDF1-4:theory-only", "DER-EM", "CODATA22"],
    ...confidence(
      "high",
      "A (linear semi-infinite good conductor; not thermal penetration depth)",
      "A maps to high inside the analytical domain.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("D-05", {
    inputParameterIds: [
      "Rdc/geometry/length",
      "frequency/material_state",
      "field_exposed_surfaces",
      "method_id",
    ],
    outputQuantityIds: ["Rac", "Rac/Rdc", "Aeff", "unaccounted proximity term"],
    applicabilityDomain:
      "Top-level method family. The screening child is only a strong-skin, approximately uniform-surface-field estimate; measured same-state port AC resistance is the preferred child.",
    warningPredicates: [
      "round-section screening is used for rectangular or complex geometry",
      "ro/delta<10",
      "hollow-tube t_wall/delta<3",
      "external field or return path is unknown",
      "proximity effect is significant",
      "an unsourced Fprox is used",
      "loaded-port active resistance is labelled coil Rac",
    ],
    warningIds: [],
    validationCaseIds: ["EXP-RAC-001"],
    methodCheckIds: ["ELEC-RAC-FREEZE-001"],
    validationNotes: "ELEC-RAC-FREEZE-001 specified; EXP-RAC-001 central case specified but not executed.",
    sourceRefs: [
      "ID-EM-01",
      "RG12:PDF172-187:future-full-frequency-candidate",
      "DHT:PDF8,17-18",
      "DER-EM",
    ],
    ...confidence(
      "engineering_approximation",
      "C (strong-skin uniform-surface screening; measurement preferred; general proximity deferred)",
      "C maps to engineering_approximation for the registered screening family summary.",
    ),
    ...recommendation(
      null,
      "D-05 is a parent calculation family that must be split; the measured child is preferred but the top-level family is not itself a recommendation candidate.",
    ),
  }),
  contractMetadata("D-06", {
    inputParameterIds: ["current_rms", "Ametal", "Aeff", "Rac"],
    outputQuantityIds: ["Jdc", "J_eff", "Pcu"],
    applicabilityDomain:
      "RMS port, section definition and Rac physical boundary are explicit; J values are averages, not local hotspots.",
    warningPredicates: [
      "peak current is used as RMS",
      "Aeff is not approved",
      "Rac is back-calculated from the same Pcu and creates a cycle",
      "a local peak is labelled an average",
    ],
    warningIds: [],
    validationCaseIds: ["EXP-RAC-001"],
    methodCheckIds: ["ELEC-PCU-001"],
    validationNotes: "ELEC-PCU-001 specified with TOL-ID; EXP-RAC-001 central case specified.",
    sourceRefs: ["ID-OHM-02", "D-05 or F-02 same-state Rac provenance required"],
    ...confidence(
      "high",
      "A (RMS, section, reference plane and Rac source explicit)",
      "A maps to high when all stated boundaries are explicit.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("D-07", {
    inputParameterIds: ["series_resistance", "series_inductance", "frequency", "current_rms"],
    outputQuantityIds: ["XL", "Zcomplex", "|Z|", "Qs", "UR", "UX", "Uterminal"],
    applicabilityDomain:
      "Linear sinusoidal series equivalent at one frequency and one RMS port; resonant-tank and grid ports must not be mixed.",
    warningPredicates: [
      "Rs=0 but a finite Q is emitted",
      "peak and RMS quantities are mixed",
      "UX is labelled grid voltage",
      "resonant-tank port is undefined",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["ELEC-ZS-001"],
    validationNotes: "ELEC-ZS-001 specified with TOL-ID.",
    sourceRefs: ["ID-AC-01", "DER-CIRCUIT"],
    ...confidence(
      null,
      "A (same frequency and port); U approximately IomegaL only C",
      "The source row assigns A to the exact port algebra but C to an included approximation; the parent record must be split or the approximation excluded before one machine value is assigned.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("E-01", {
    inputParameterIds: [
      "frequency",
      "workpiece.resistivity_snapshot",
      "workpiece.relative_permeability_snapshot",
      "characteristic_thickness/radius",
    ],
    outputQuantityIds: ["delta_w", "t/delta", "R/delta", "property provenance"],
    applicabilityDomain:
      "Linear homogeneous isotropic good conductor, sinusoidal steady state and local semi-infinite plane; thin walls, Curie behavior and unusual geometry are reference-only uses.",
    warningPredicates: [
      "t or R is comparable with a few skin depths",
      "magnetic saturation or Curie transition",
      "thin-wall fields act from both faces",
      "edge, end, slot or unusual geometry",
      "electromagnetic skin depth is called thermal penetration depth",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["EM-S-004", "EM-S-003"],
    validationNotes: "EM-S-004 and EM-S-003 executed_pass.",
    sourceRefs: ["ID-EM-01", "JM95:PDF1-4", "M04:PDF2:eq1", "DER-EM", "CODATA22"],
    ...confidence(
      "high",
      "A (linear semi-infinite); thin wall, Curie and unusual geometry reference only",
      "A maps to high only inside the linear semi-infinite domain.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("E-02", {
    inputParameterIds: ["temperature_grid", "frequency/field_state", "rho/mu datasets"],
    outputQuantityIds: ["rho(Ti)", "mu_r(Ti)", "delta(Ti)", "scenario bands"],
    applicabilityDomain:
      "Property data must match material, field and frequency and the temperature grid must resolve the transition; otherwise return insufficient_data.",
    warningPredicates: [
      "only one cold-state property point exists",
      "fixed mu_r is used across Curie",
      "generic 700 C or 760 C Curie value is assigned to all steels",
      "property data are extrapolated",
      "H or f is missing",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["EM-S-003"],
    validationNotes:
      "EM-S-003 executed_pass; the real-grade curve check is blocked without a method_check_id because the material package is missing.",
    sourceRefs: ["S89:PDF1-5:scope-evidence", "actual material table source missing"],
    ...confidence(
      null,
      "C (method A; concrete data VFY per material)",
      "The audit summary mixes method and dataset judgments and cannot be stored as one method-level machine confidence.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("E-03", {
    inputParameterIds: [
      "workpiece.diameter",
      "rho_at_target_state",
      "mu_r_at_target_state",
      "penetration_criterion",
    ],
    outputQuantityIds: ["Pi_D", "fref"],
    applicabilityDomain:
      "Empirical reference point for a solid cylinder at the target material state; not applicable to thin-wall tube and not an optimum-frequency result.",
    warningPredicates: [
      "ohm-centimetre and microohm-centimetre constants are mixed",
      "thin-wall workpiece",
      "cold properties are used for the hot state",
      "result is labelled recommended or optimum without process optimization",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["EM-F-001"],
    validationNotes: "EM-F-001 executed_pass; historical image8 bounds are audit_only and not validation.",
    sourceRefs: ["M04:PDF2-3:PRINT72-73:eq1-5", "ID-EM-01", "DER-EM"],
    ...confidence(
      "engineering_approximation",
      "C (solid-cylinder empirical reference; not optimum frequency)",
      "C maps to engineering_approximation.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("F-01", {
    inputParameterIds: [
      "primary.resistance/inductance",
      "secondary.resistance/inductance",
      "mutual_inductance",
      "frequency",
    ],
    outputQuantityIds: ["Zin", "Req", "Rref", "Leq", "k"],
    applicabilityDomain:
      "Given same-state linear lumped parameters only; the algebra does not derive M, R2 or Ls from geometry.",
    warningPredicates: [
      "|k|>1",
      "Rref<0",
      "parameters come from different frequencies or temperatures",
      "Leq/L0 is called k",
      "M is guessed when geometry-to-parameter evidence is missing",
    ],
    warningIds: [],
    validationCaseIds: ["EM-Z-001"],
    methodCheckIds: ["EM-Z-PASSIVITY-001"],
    validationNotes: "EM-Z-001 central case specified; EM-Z-PASSIVITY-001 specified.",
    sourceRefs: ["ID-Z-01", "DER-CIRCUIT", "J08:PDF2-3:scope-only", "L13:PDF1-6:scope-only"],
    ...confidence(
      "high",
      "A (given linear lumped parameters); geometry cannot automatically supply the parameters",
      "A maps to high for the given-parameter circuit algebra only.",
    ),
    ...recommendation("not_eligible", "The basis labels F-01 an estimate and explicitly states that F-02 same-state measurement is more accurate."),
  }),
  contractMetadata("F-02", {
    inputParameterIds: [
      "voltage/current_rms",
      "active_power",
      "frequency",
      "reactive_sign/phase",
      "measurement_uncertainty",
    ],
    outputQuantityIds: ["|Z|", "Req", "X", "Leq", "Qs", "uncertainty"],
    applicabilityDomain:
      "Approximately sinusoidal fundamental or explicitly defined full-wave measurements, de-embedded fixture/leads and steady same-temperature state.",
    warningPredicates: [
      "P>VI beyond uncertainty",
      "|Z|^2-Req^2 is negative beyond propagated uncertainty",
      "Leq is emitted from P and I only",
      "true PF and cos(phi) are mixed",
      "temperature drifts during measurement",
    ],
    warningIds: [],
    validationCaseIds: ["EM-Z-002"],
    methodCheckIds: ["EM-Z-LOWQ-001", "EM-Z-ACTUAL-001"],
    validationNotes: "EM-Z-002 central case specified; EM-Z-LOWQ-001 specified; EM-Z-ACTUAL-001 blocked.",
    sourceRefs: ["ID-MEAS-01", "DHT:PDF17-18", "DER-CIRCUIT"],
    ...confidence(
      "high",
      "A (measurement definition, de-embedding and uncertainty complete)",
      "A maps to high when all measurement-boundary requirements are satisfied.",
    ),
    ...recommendation("eligible", "CALCULATION_BASIS explicitly labels F-02 the actual-equipment Recommended method."),
  }),
  contractMetadata("F-03", {
    inputParameterIds: [
      "equipment_family_id",
      "cases_calibration[]",
      "cases_validation[]",
      "feature/model_spec",
    ],
    outputQuantityIds: [
      "per-output estimate",
      "signed error",
      "MAE/RMSE/max relative error",
      "sample counts",
      "multidimensional calibration domain",
      "model uncertainty",
    ],
    applicabilityDomain:
      "Future stable equipment family, reference plane and measured state, with new frozen calibration and independent validation data; domain exit is not_applicable.",
    warningPredicates: [
      "the same case is used for calibration and validation",
      "single-case correction",
      "historical data enter the dataset",
      "reference planes or equipment families are mixed",
      "calibration-domain extrapolation",
      "identity-derived columns are counted as independent targets",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: [],
    validationNotes:
      "No central validation_case_id has been assigned. Calibration, independent validation and sealed-holdout cases must first be created; current result is insufficient_data.",
    sourceRefs: ["ADR-0002", "ADR-0004", "ADR-0008", "future model formula not registered"],
    ...confidence(
      null,
      "Deferred; historical data product disabled",
      "Deferred is a disposition, not a scientific_confidence enum, so no machine confidence is assigned.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-01", {
    inputParameterIds: ["mass(m)", "Ti", "Tf", "cp(T)", "phase/reaction_enthalpy"],
    outputQuantityIds: ["Esens", "Euseful"],
    applicabilityDomain:
      "Uniform batch and explicit control volume; constant cp is approved only over a narrow stated temperature domain.",
    warningPredicates: [
      "Tf<=Ti -> invalid_input",
      "phase boundary is crossed without enthalpy data",
      "cp is extrapolated",
      "furnace and fluid control volumes are mixed",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["TH-E-001"],
    validationNotes:
      "TH-E-001 specified with TOL-ID; temperature-table integration and phase-node check specified with TOL-NUM but no separate method_check_id.",
    sourceRefs: ["ID-TH-01", "DER-ENERGY:pending-sign-off", "per-property source"],
    ...confidence(
      "high",
      "A (control volume and enthalpy data explicit)",
      "A maps to high when the boundary and enthalpy inputs are explicit.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-02", {
    inputParameterIds: ["mass_flow(mdot)", "hin", "hout", "T+cp+delta_h"],
    outputQuantityIds: ["Puseful"],
    applicabilityDomain: "Steady single stream or explicit sum of multiple streams.",
    warningPredicates: [
      "mass in kg is used as mass flow in kg/s",
      "reaction-enthalpy sign or reference state is unknown",
      "startup furnace heating is counted as steady process-flow power",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["TH-E-002"],
    validationNotes: "TH-E-002 specified with TOL-ID; real process enthalpy data check blocked without a separate ID.",
    sourceRefs: ["ID-TH-01", "DER-ENERGY", "process data missing"],
    ...confidence("high", "A", "A maps to high."),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-03", {
    inputParameterIds: [
      "thermal_mass/cp(T)",
      "Pabs(T,t)",
      "Qloss(T,t)",
      "Pphase(T)",
      "T0",
      "target",
      "solver settings",
    ],
    outputQuantityIds: ["T(t)", "time_to_target", "energy_residual"],
    applicabilityDomain:
      "Lumped thermal capacity only after Biot screening; the constant-net-power shortcut only when net power is constant.",
    warningPredicates: [
      "Pnet<=0 -> target_unreachable",
      "Bi is too large for lumping",
      "a single constant step crosses Curie or phase change",
      "solver does not converge",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: [],
    validationNotes:
      "Constant-net-power analytical comparison specified at rtol<=1e-6; measured temperature-rise validation blocked. Neither note has a frozen ID.",
    sourceRefs: ["ID-TH-01", "DER-ENERGY", "experiment data missing"],
    ...confidence(
      null,
      "A/C (lumped-model applicability must be checked)",
      "A/C is a composite audit summary and cannot be normalized without splitting the exact balance from the lumped approximation.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-04", {
    inputParameterIds: ["Pgrid", "Pinv", "Pcoil", "Pwp", "Puseful", "Pcu", "Qloss"],
    outputQuantityIds: ["eta_inv", "eta_coil_wp", "eta_thermal", "eta_overall", "missing boundary"],
    applicabilityDomain: "Only ratios whose numerator and denominator share a consistent named control-volume boundary and time basis.",
    warningPredicates: [
      "denominator is zero",
      "efficiency exceeds one beyond uncertainty",
      "overall and staged efficiencies are multiplied twice",
      "reactive power is counted as loss",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["SYS-P-001"],
    validationNotes: "SYS-P-001 specified with TOL-ID; conservation property specified without a separate ID.",
    sourceRefs: ["ID-TH-01", "DER-ENERGY", "DER-CIRCUIT"],
    ...confidence(
      "high",
      "A (definition); historical total efficiency audit_only and prohibited from runtime/calibration/validation",
      "A maps to high for the frozen boundary definitions; the historical aggregate is excluded.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-05", {
    inputParameterIds: [
      "Puseful",
      "Qloss_wp",
      "Pcu",
      "Pstray",
      "eta_matching",
      "eta_inv",
      "eta_rect",
      "eta_other",
    ],
    outputQuantityIds: ["Pwp_abs", "Pcoil_terminal", "Pgrid", "unknown items"],
    applicabilityDomain: "Explicit non-overlapping control-volume losses and efficiency boundaries only.",
    warningPredicates: [
      "unknown loss is silently set to zero",
      "efficiency boundaries overlap",
      "eta=0",
      "peak and average powers are mixed",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["SYS-P-002"],
    validationNotes: "SYS-P-002 specified with TOL-ID.",
    sourceRefs: ["ID-TH-01", "DER-ENERGY", "per-device efficiency source"],
    ...confidence(
      "high",
      "A (no repeated losses or efficiencies)",
      "A maps to high when all boundaries are non-overlapping.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-06", {
    inputParameterIds: ["Vrms", "Irms", "P", "phase_count/topology", "ULL"],
    outputQuantityIds: ["S", "PF"],
    applicabilityDomain: "Same explicit port; balanced three-phase relation only for a balanced three-phase topology.",
    warningPredicates: [
      "P>S beyond uncertainty",
      "cos(phi) is used as true PF",
      "coil-terminal and grid-side quantities are mixed",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["ELEC-PF-001"],
    validationNotes: "ELEC-PF-001 specified with TOL-ID.",
    sourceRefs: ["ID-AC-02", "DER-CIRCUIT", "primary standard page missing"],
    ...confidence(
      "high",
      "A (definition); formal normative source still requires freezing",
      "A maps to high for the definition while the source-location gap remains explicit.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-07", {
    inputParameterIds: ["R", "L", "C", "f", "port/RMS definition"],
    outputQuantityIds: ["Zs", "f0", "C_for_f"],
    applicabilityDomain: "Only an explicitly identified lumped series single-resonance network.",
    warningPredicates: [
      "topology is unknown",
      "unloaded L replaces hot loaded L without warning",
      "parallel or LLC topology uses the series method",
      "parasitics are ignored",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["ELEC-RLC-S-001"],
    validationNotes: "ELEC-RLC-S-001 specified.",
    sourceRefs: ["ID-RLC-01", "DER-CIRCUIT", "primary textbook page missing"],
    ...confidence(
      "high",
      "A (only the explicit series single-resonance topology)",
      "A maps to high inside the named topology.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-08", {
    inputParameterIds: ["topology", "R", "L", "C", "f"],
    outputQuantityIds: ["Yin", "Zin", "f0", "branch V/I"],
    applicabilityDomain:
      "Only the frozen ideal parallel R/L/C or series-RL branch parallel C topology, with positive roots and an explicit port.",
    warningPredicates: [
      "series-loss R is treated as parallel R",
      "a nonpositive root is reported as resonance",
      "series-network stress relations are reused",
      "parasitics are ignored",
    ],
    warningIds: [],
    validationCaseIds: ["PWR-PAR-IDEAL-001", "PWR-PAR-RL-001"],
    methodCheckIds: [],
    validationNotes: "Both central cases are specified.",
    sourceRefs: ["ID-RLC-02", "ADR-0007", "DER-CIRCUIT"],
    ...confidence(
      null,
      "A/C (only the corresponding topology, positive root and port)",
      "A/C is a composite family summary and cannot be normalized before the two topologies are registered separately.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-09", {
    inputParameterIds: [
      "complete_netlist",
      "ports",
      "Ls",
      "Lm/Leq",
      "Cs/Cp",
      "Req",
      "drive_harmonics",
    ],
    outputQuantityIds: ["Zin", "gain", "branch stresses", "characteristic frequencies"],
    applicabilityDomain:
      "Only the exact thesis topology and its FHA/high-Q assumptions; the top-level general LLC method is deferred.",
    warningPredicates: [
      "circuit diagram is missing",
      "high-Q relation is used at low Q",
      "thesis-specific values are generalized",
      "FHA result is not labelled FHA",
    ],
    warningIds: [],
    validationCaseIds: ["PWR-LLC-ZJL-001"],
    methodCheckIds: [],
    validationNotes:
      "PWR-LLC-ZJL-001 central case specified, reference_only; it does not change the deferred method disposition and runtime remains insufficient_data.",
    sourceRefs: ["LLC-ZJL:PDF24-33", "LLC-ZJL:PDF64-65", "Fig2.6", "eq2.13", "eq2.16", "no general LLC source"],
    ...confidence(
      "engineering_approximation",
      "C (same topology and assumptions only); high-Q relation prohibited at low Q",
      "C maps to engineering_approximation for the cited topology-specific candidate, without enabling the deferred parent.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("G-10", {
    inputParameterIds: ["Zs", "n=Np/Ns", "port/RMS/fundamental definitions"],
    outputQuantityIds: ["Zp", "Vp/Vs", "Is/Ip"],
    applicabilityDomain: "Ideal lossless transformer with explicit ratio direction and port/RMS/fundamental definitions.",
    warningPredicates: [
      "turns-ratio direction is reversed",
      "rectifier factor crosses topology boundaries",
      "fundamental and full-wave port quantities are mixed",
      "core saturation is ignored",
    ],
    warningIds: [],
    validationCaseIds: ["PWR-XFMR-001"],
    methodCheckIds: [],
    validationNotes: "PWR-XFMR-001 central case specified.",
    sourceRefs: ["ID-Z-02", "ADR-0007", "DER-CIRCUIT"],
    ...confidence(
      "high",
      "A (ideal lossless transformer with explicit port/RMS definitions)",
      "A maps to high inside the ideal-transformer domain.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("H-01", {
    inputParameterIds: ["Pcu", "Qpickup_to_coil", "Pmag", "Pother", "design_margin"],
    outputQuantityIds: ["Qcool", "per-item provenance", "unaccounted items"],
    applicabilityDomain: "Each heat source and coolant circuit/control volume is explicit; design margin is an explicit scenario.",
    warningPredicates: [
      "useful workpiece heat, reactive power or plant-wide loss enters coil coolant load",
      "unknown pickup is silently included or set to zero",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["COOL-CONTROL-001"],
    validationNotes: "COOL-CONTROL-001 specified.",
    sourceRefs: ["ID-HYD-01", "DHT:PDF10-12", "DER-ENERGY", "ADR-0006"],
    ...confidence(
      "high",
      "A (each term source and circuit explicit)",
      "A maps to high for the explicit control-volume balance.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("H-02", {
    inputParameterIds: ["Qcool", "Tin", "Tout", "pin", "pout", "h", "rho"],
    outputQuantityIds: ["mdot", "Vdot"],
    applicabilityDomain:
      "Single-phase water and explicit heat boundary; constant-property form only as an explicit narrow-domain approximation.",
    warningPredicates: [
      "enthalpy difference is nonpositive",
      "gauge pressure is used",
      "phase boundary is crossed",
      "constant properties exceed their stated domain",
      "a universal cooling multiplier is used",
    ],
    warningIds: [],
    validationCaseIds: ["COOL-ENERGY-001"],
    methodCheckIds: [],
    validationNotes: "COOL-ENERGY-001 central case specified.",
    sourceRefs: ["ID-HYD-01", "IAPWS-95/IF97", "DER-ENERGY", "local IAPWS hash missing"],
    ...confidence(
      "high",
      "A (single phase and heat boundary explicit); fixed kcool X",
      "A maps to high for the enthalpy method; X applies only to the rejected fixed multiplier.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("H-03", {
    inputParameterIds: ["Vdot_branch", "Ah", "Pwetted", "network split"],
    outputQuantityIds: ["v", "Dh"],
    applicabilityDomain: "Flow may be evenly split only between branches known to have equal resistance.",
    warningPredicates: [
      "total flow is passed to one branch",
      "mass flow is labelled velocity",
      "asymmetric branches are evenly split",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["COOL-GEO-001"],
    validationNotes: "COOL-GEO-001 specified.",
    sourceRefs: ["ID-HYD-01", "DER-HYD"],
    ...confidence(
      "high",
      "A; historical workbook J27/J28 X",
      "A maps to high for continuity; X applies only to the rejected historical workbook cells.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("H-04", {
    inputParameterIds: [
      "rho",
      "v",
      "Dh",
      "mu",
      "cp",
      "kf",
      "geometry",
      "development",
      "heat_bc",
      "method_id",
    ],
    outputQuantityIds: ["Re", "Pr", "Nu", "h"],
    applicabilityDomain:
      "Straight circular tube under the selected correlation's strict domain; Gnielinski requires 1e4<=Re<=5e6 and 0.5<=Pr<=2000. Helical, entrance, noncircular and two-phase methods are deferred.",
    warningPredicates: [
      "transition-flow interpolation",
      "straight-tube correlation is applied to helical, entrance, noncircular or two-phase flow",
      "mean h is labelled hotspot safety",
    ],
    warningIds: [],
    validationCaseIds: ["EXP-COOL-001"],
    methodCheckIds: ["COOL-GNIELINSKI-001"],
    validationNotes: "COOL-GNIELINSKI-001 specified; EXP-COOL-001 central case specified.",
    sourceRefs: ["ID-HYD-01", "GN75:PP8-16", "NASA-NTRS-19830022277:S6.1.2.1", "OSTI-836896:S3.1.1"],
    ...confidence(
      "engineering_approximation",
      "C (strict straight-round-tube domain; helical, entrance, noncircular and two-phase deferred)",
      "C maps to engineering_approximation.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("H-05", {
    inputParameterIds: ["L", "Dh", "rho", "v", "epsilon", "sumK", "Deltaz", "network", "pump_curve"],
    outputQuantityIds: ["Delta p components", "branch flows", "workpoint"],
    applicabilityDomain:
      "Straight circular pipe with known roughness for the registered relations; Colebrook requires Re>=1e4. Transition and helical final design are deferred.",
    warningPredicates: [
      "Darcy and Fanning factors are mixed",
      "roughness or local-loss coefficient is unknown",
      "transition flow",
      "helical-pipe result is presented as final",
      "reachability is claimed without a pump curve",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["COOL-COLEBROOK-001"],
    validationNotes: "COOL-COLEBROOK-001 specified; measured pressure-drop check blocked without a frozen ID.",
    sourceRefs: ["ID-HYD-02", "C39:PP133-156", "NIST-TN2294:REPORT-P23"],
    ...confidence(
      "engineering_approximation",
      "C (straight circular pipe and known roughness; transition and helical deferred)",
      "C maps to engineering_approximation.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("H-06", {
    inputParameterIds: ["Tb", "Twi", "pabs", "Tsat", "water_quality", "NPSHA/NPSHR"],
    outputQuantityIds: ["DeltaT_sub_bulk/wall", "NPSH comparison", "missing data"],
    applicabilityDomain:
      "Raw saturation and NPSH margins may be calculated; safety thresholds require matching OEM/project data and common reference bases.",
    warningPredicates: [
      "a positive raw margin is called safe",
      "outlet temperature substitutes for hotspot temperature",
      "OEM data or pump curve is missing",
      "gauge pressure is used",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["COOL-WARN-001"],
    validationNotes: "COOL-WARN-001 specified; local-hotspot test blocked without a frozen ID.",
    sourceRefs: ["IAPWS-IF97:Region4", "HI-961", "ANSI/HI-9.6.1", "DHT:PDF11-12,17", "OEM/project data"],
    ...confidence(
      "engineering_approximation",
      "C (raw margins calculable; safety thresholds require OEM/project data)",
      "C maps to engineering_approximation and does not imply a safety decision.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("H-07", {
    inputParameterIds: ["mdot", "Tin", "Tout", "pin", "pout", "Qmodel", "time_basis", "control_volume"],
    outputQuantityIds: ["Qwater", "residual", "uncertainty"],
    applicabilityDomain: "Measured and modeled quantities must share the same coolant circuit, control volume and time basis.",
    warningPredicates: [
      "different circuits or time periods are compared",
      "measurement is automatically altered to match the model",
      "an average is labelled a local peak",
    ],
    warningIds: [],
    validationCaseIds: ["COOL-ENERGY-001", "EXP-COOL-001"],
    methodCheckIds: [],
    validationNotes: "Both central cases are specified.",
    sourceRefs: ["ID-HYD-01", "DER-ENERGY", "ADR-0006", "ADR-0008"],
    ...confidence(
      "high",
      "A; historical cooling quantities excluded from input/calibration/validation",
      "A maps to high for the same-boundary balance; historical quantities remain excluded.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("J-01", {
    inputParameterIds: ["ri", "ro", "L", "Ti", "To", "k or k(T)", "layer radii"],
    outputQuantityIds: ["Rcond", "Qcond", "interface T"],
    applicabilityDomain:
      "One-dimensional radial cylindrical conduction; variable-property and multilayer cases use the registered integration/interface process. End and bridge paths are separate.",
    warningPredicates: [
      "radius and diameter are mixed",
      "k is extrapolated or wet-state k is missing",
      "end or bridge loss is omitted",
      "a disputed standard print is implemented directly",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["INS-FOURIER-001", "INS-VARK-001"],
    validationNotes: "INS-FOURIER-001 and INS-VARK-001 specified.",
    sourceRefs: ["ID-HT-01", "Fourier", "DER-THERM", "GB8175:PDF7:eq7:conflict-not-source"],
    ...confidence(
      "high",
      "A (controlled Fourier derivation); GB8175 printed eq.7 X/VFY correction",
      "A maps to high for the controlled derivation; the disputed printed standard equation is not used.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("J-02", {
    inputParameterIds: [
      "geometry",
      "orientation",
      "Lc",
      "Ts",
      "Tinf",
      "fluid props",
      "U/wind",
      "method_id",
    ],
    outputQuantityIds: ["Ra/Re", "Pr", "Nu", "hc", "Qconv", "domain"],
    applicabilityDomain:
      "Only the selected CC75 vertical plate, CC75 horizontal cylinder, or CB77 cylinder cross-flow child correlation with its original characteristic length and domain.",
    warningPredicates: [
      "arbitrary inclination, mixed convection, array or shielding is unmodeled",
      "fixed h has no source",
      "max or power-sum method mixing is used",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["CONV-CC75-V-001", "CONV-CC75-H-001", "CONV-CB77-001"],
    validationNotes: "All three correlation method checks are specified.",
    sourceRefs: ["ID-HT-01", "CC75-V:PP1323-1329", "CC75-H:PP1049-1053", "CB77:PP300-306"],
    ...confidence(
      null,
      "A (heat-transfer identity); C (only matching vertical plate/horizontal cylinder/cross-flow cylinder correlations)",
      "The audit row mixes an analytical identity and three engineering correlations; child-method splitting is required for one machine value.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("J-03", {
    inputParameterIds: ["T1", "T2", "epsilon1/2", "A1/2", "view/configuration"],
    outputQuantityIds: ["Qrad", "network factor"],
    applicabilityDomain: "Radiation to large surroundings or the supported long concentric two-gray-surface network with explicit areas and view/configuration.",
    warningPredicates: [
      "Celsius temperatures are raised to the fourth power",
      "equal-area simplification is misapplied",
      "view factor or opening is ignored",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["RAD-001"],
    validationNotes: "RAD-001 specified.",
    sourceRefs: ["ID-RAD-01", "Stefan-Boltzmann", "GB8175:PDF14-16:AnnexA:eqA.2", "DER-THERM", "CODATA22"],
    ...confidence(
      "high",
      "A (boundary, area and view factor explicit)",
      "A maps to high when the network boundary is explicit.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("J-04", {
    inputParameterIds: ["epsilon", "Ts", "Tsur", "hc"],
    outputQuantityIds: ["hr", "hs"],
    applicabilityDomain: "Only coefficients belonging to the same area and boundary and inside the J-02/J-03 domains.",
    warningPredicates: [
      "0/0 is not protected at equal temperatures",
      "coefficients from different areas or boundaries are added",
      "linearized hr is used over a large temperature interval without update",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: [],
    validationNotes: "Equal-temperature limit versus direct radiation specified at rtol<=1e-10; no method_check_id is frozen.",
    sourceRefs: ["GB8175:AnnexA:eqA.2", "ID-RAD-01", "DER-THERM", "CODATA22"],
    ...confidence(
      "high",
      "A (same area and boundary)",
      "A maps to high inside the same-area/same-boundary domain.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("J-05", {
    inputParameterIds: [
      "L",
      "orientation",
      "closure",
      "outer_continuity",
      "T_hot",
      "T_cold",
      "gas props",
      "D_i+D_ins_o or s_ann+geometry_mapping_id+uncertainty",
      "e_ann",
      "view",
      "path_id",
    ],
    outputQuantityIds: [
      "classification",
      "s_ann",
      "geometry_residual",
      "Ra",
      "Pr",
      "Nu/keff",
      "hgap",
      "Qgas",
      "Qrad",
      "domain",
    ],
    applicabilityDomain:
      "Continuous closed horizontal annulus under RH75 or continuous closed vertical annulus under DT69. Open, discrete, eccentric or otherwise complex paths are deferred.",
    warningPredicates: [
      "diameter difference is used directly as one-sided gap",
      "bare s_ann lacks geometry_mapping_id and uncertainty",
      "measurement silently overrides mechanical diameters",
      "unknown eccentricity defaults to zero",
      "g is reused for annulus gap",
      "closed-annulus correlation is used for open, discrete or eccentric geometry",
      "water temperature substitutes for copper temperature",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["ANN-H-001", "ANN-V-001", "ANN-GEOMETRY-RESIDUAL-001", "ANN-OPEN-FAIL-001"],
    validationNotes: "All four method checks are specified.",
    sourceRefs: [
      "RH75",
      "Kuehn-Goldstein-1976:DOI10.1016/0017-9310(76)90145-9",
      "DT69",
      "ONWI-229:PDF24-28",
      "ADR-0006",
    ],
    ...confidence(
      "engineering_approximation",
      "C (two continuous closed-annulus classes); open/discrete/eccentric complex paths deferred",
      "C maps to engineering_approximation for the two supported correlation classes.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("J-06", {
    inputParameterIds: ["Qconv", "Qrad", "Qends", "Qbridges", "Qopenings", "control_volume"],
    outputQuantityIds: ["Qloss_total", "missing_items", "boundary"],
    applicabilityDomain: "One explicit control volume with non-overlapping path areas and no duplicate heat-flow path.",
    warningPredicates: [
      "series-path heat flows are added",
      "unknown end or bridge loss is set to zero",
      "inductive pickup and ambient heat loss are mixed",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["THERM-BAL-001"],
    validationNotes: "THERM-BAL-001 specified.",
    sourceRefs: ["ID-HT-01", "DER-THERM", "DER-ENERGY"],
    ...confidence(
      "high",
      "A (same control volume and no duplication); end model not yet defined",
      "A maps to high for the sum identity while missing end models remain explicit outputs.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("J-07", {
    inputParameterIds: ["T(t)", "geometry", "h", "k", "epsilon", "thermal mass"],
    outputQuantityIds: ["Qloss(t)", "Bi"],
    applicabilityDomain:
      "Calls current J components at every state; Bi is screening only and no unapproved threshold may automatically claim lumped precision.",
    warningPredicates: [
      "large Bi still uses the lumped model",
      "h or k is not updated",
      "end or bridge time dependence is missing",
      "Bi threshold has no source",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: [],
    validationNotes:
      "First-order lumped analytical cooling check specified at rtol<=1e-6; distributed-temperature case blocked. Neither note has a frozen ID.",
    sourceRefs: ["ID-HT-02", "DER-THERM", "primary textbook page and Bi threshold missing"],
    ...confidence(
      null,
      "C/VFY (method correct; lumped threshold and geometry definition await source approval)",
      "C/VFY is a composite audit summary and cannot be normalized before the threshold/domain evidence is frozen.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("I-01", {
    inputParameterIds: [
      "ri",
      "L",
      "Ti",
      "Ts_target",
      "Ta",
      "Tsur",
      "k(T)",
      "epsilon",
      "hc_method",
      "delta_domain",
      "rounding",
    ],
    outputQuantityIds: ["ro", "delta", "Q", "interface T", "residual", "feasible_intervals"],
    applicabilityDomain:
      "One-dimensional radial sidewall model; finite design-domain scan retains all physical solutions, selects the minimum feasible interval, rounds upward and fully recomputes.",
    warningPredicates: [
      "no root and no feasible solution are conflated",
      "material maximum temperature is exceeded",
      "convection method is out of domain",
      "end or bridge loss is missing",
      "rounded design is not recomputed",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["INS-FOURIER-001", "INS-ROUND-001"],
    validationNotes: "INS-FOURIER-001 and INS-ROUND-001 specified.",
    sourceRefs: ["ID-HT-01", "DER-THERM", "GB8175:PDF10:PRINT6:eq24:limited-check"],
    ...confidence(
      "high",
      "A (closed model); each correlation and property remains domain-limited",
      "A maps to high for the coupled solve; dependency domains remain independent gates.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("I-02", {
    inputParameterIds: [
      "ri",
      "L",
      "Ti",
      "Ta",
      "Tsur",
      "k(T)",
      "epsilon",
      "hc_method",
      "exactly one of Qlimit,q'_limit,q''_limit with area basis",
      "design domain",
    ],
    outputQuantityIds: [
      "ro",
      "delta",
      "Ts",
      "Qactual",
      "all_physical_roots",
      "feasible_intervals",
      "residual",
    ],
    applicabilityDomain:
      "Complete surface balance over a finite design domain with all physical roots and feasible intervals; the disputed printed standard equation is not implemented.",
    warningPredicates: [
      "negative-temperature root",
      "wrong root is silently selected from multiple roots",
      "q'' area basis is unknown",
      "critical-radius nonmonotonicity is ignored",
      "end heat loss is unknown",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["INS-DUAL-NONMONO-001"],
    validationNotes: "INS-DUAL-NONMONO-001 specified.",
    sourceRefs: ["ID-HT-01", "DER-THERM", "GB8175:PDF10:PRINT6:eq20:rejected-as-printed"],
    ...confidence(
      "high",
      "A (complete coupled derivation); GB8175 eq.20 X pending correction",
      "A maps to high for the controlled coupled derivation; the rejected printed equation is excluded.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("I-03", {
    inputParameterIds: ["I-01 complete inputs", "I-02 loss limit"],
    outputQuantityIds: ["delta_design", "Ts", "Q", "pass_flags", "feasible_intersection"],
    applicabilityDomain:
      "Intersection of temperature, heat-loss and manufacturing feasible sets; max(delta_T,delta_Q) is allowed only after proving both constraint sets are upward closed.",
    warningPredicates: [
      "empty intersection is reported as non-convergence",
      "max(delta_T,delta_Q) is used unconditionally",
      "rounded result is not recomputed",
      "end or bridge boundaries differ between constraints",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["INS-DUAL-NONMONO-001", "INS-ROUND-001"],
    validationNotes: "Both method checks are specified.",
    sourceRefs: ["ID-HT-01", "ADR-0006", "DER-THERM"],
    ...confidence(
      null,
      "A/C (algorithm and finite-domain solve; dependent on J-method and property domains)",
      "A/C is a composite audit summary and cannot be normalized without separating the exact set operation from approximate dependencies.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
  contractMetadata("I-04", {
    inputParameterIds: ["ri", "delta", "k", "h(or nonlinear surface model)"],
    outputQuantityIds: ["delta/ri", "rcrit", "screening status", "optional nonlinear loss curve"],
    applicabilityDomain:
      "Fixed-h and fixed-k cylindrical screening only; radiation or variable h/k requires the full nonlinear curve and the screen is not an exact design conclusion.",
    warningPredicates: [
      "rcrit is treated as exact with radiation or variable h/k",
      "project QA threshold is called a standard threshold",
      "screening replaces the insulation root solve",
    ],
    warningIds: [],
    validationCaseIds: [],
    methodCheckIds: ["INS-SCREEN-001"],
    validationNotes: "INS-SCREEN-001 specified with TOL-ID; plane-wall ratio curve specified without a separate ID.",
    sourceRefs: ["ID-HT-01", "V1_CONTROLLED_DERIVATIONS", "DER-THERM"],
    ...confidence(
      "engineering_approximation",
      "C (screening); not exact with radiation or variable h/k",
      "C maps to engineering_approximation.",
    ),
    ...NO_EXPLICIT_RECOMMENDATION,
  }),
] as const;

/**
 * Frozen, read-only metadata extracted from the four Gate-0 calculation
 * contract/source/validation documents. Formulae are intentionally not
 * duplicated here; contractEquationRef and sourceRefs locate them.
 */
export const METHOD_CONTRACT_METADATA_CATALOG = Object.freeze(
  cloneAndDeepFreeze(
    Object.fromEntries(ENTRIES) as Record<MethodId, MethodContractMetadata>,
  ),
);
