import {
  methodId,
  parameterId,
  type MethodId,
  type ParameterId,
} from "../domain/ids.js";
import type { UnitId } from "../units/ids.js";
import { getUnitsForDimension } from "../units/registry.js";
import type { EngineeringModuleId } from "./methodSpecificationRegistry.js";
import { cloneAndDeepFreeze } from "./immutableRegistry.js";
import {
  ParameterRegistry,
  type ParameterAlias,
  type ParameterDefault,
  type ParameterDimension,
  type ParameterRecord,
  type ParameterRequirement,
  type ParameterRole,
} from "./parameterRegistry.js";

const PARAMETER_DICTIONARY_REF = "ENGINEERING_PARAMETER_DICTIONARY";
const ADR_0003_REF = "ADR-0003";

/**
 * Power quantities share the SI dimension W, but their display-unit families
 * retain the frozen active/heat, reactive and apparent-power semantics.
 */
export const POWER_DISPLAY_UNIT_FAMILIES = Object.freeze({
  activeOrHeat: Object.freeze(["W", "kW", "MW"] as const),
  reactive: Object.freeze(["var", "kvar"] as const),
  apparent: Object.freeze(["VA", "kVA"] as const),
});

function methods(...ids: string[]): readonly MethodId[] {
  return ids.map(methodId);
}

function ids(...values: string[]): readonly ParameterId[] {
  return values.map(parameterId);
}

function alias(
  value: string,
  note: string,
  migrationRule: ParameterAlias["migrationRule"] = "rename",
): ParameterAlias {
  return { value, scope: "migration_only", migrationRule, note };
}

function controlledDefault(
  sourceParameterIds: readonly string[],
  derivationMethod: string,
  sourceRefs: readonly string[],
  warningPredicateRefs: readonly string[] = [],
): ParameterDefault {
  return {
    kind: "controlled_derivation",
    sourceParameterIds: ids(...sourceParameterIds),
    derivationMethodId: methodId(derivationMethod),
    sourceRefs,
    warningPredicateRefs,
  };
}

interface ParameterInput {
  readonly id: string;
  readonly symbol: string;
  readonly en: string;
  readonly zh: string;
  readonly definition: string;
  readonly ownerModule: EngineeringModuleId;
  readonly dimension: ParameterDimension;
  readonly canonicalUnit: UnitId;
  readonly allowedDisplayUnits?: readonly UnitId[];
  readonly role?: ParameterRole;
  readonly requirement?: ParameterRequirement;
  readonly physicalRange: string;
  readonly applicability: string;
  readonly consumingMethods?: readonly string[];
  readonly aliases?: readonly ParameterAlias[];
  readonly default?: ParameterDefault;
  readonly definitionSourceRefs?: readonly string[];
}

function parameter(input: ParameterInput): ParameterRecord {
  return {
    parameterId: parameterId(input.id),
    symbol: input.symbol,
    engineeringName: { en: input.en, zh: input.zh },
    definition: input.definition,
    help: `${input.definition} Applicability: ${input.applicability}`,
    ownerModule: input.ownerModule,
    dimension: input.dimension,
    canonicalUnit: input.canonicalUnit,
    allowedDisplayUnits:
      input.allowedDisplayUnits ??
      (input.dimension === "power"
        ? POWER_DISPLAY_UNIT_FAMILIES.activeOrHeat
        : getUnitsForDimension(input.dimension).map((definition) => definition.id)),
    role: input.role ?? "input",
    requirement: input.requirement ?? "method_dependent",
    physicalRange: input.physicalRange,
    applicability: input.applicability,
    definitionSourceRefs: input.definitionSourceRefs ?? [PARAMETER_DICTIONARY_REF],
    default: input.default ?? null,
    aliases: input.aliases ?? [],
    consumingMethods: methods(...(input.consumingMethods ?? [])),
    dataQualityPolicy: "runtime_quantity_must_carry_data_quality",
    precisionPolicy: "derive_from_input_resolution_and_uncertainty",
  };
}

/** Frozen dictionary metadata only; no engineering equation is executed here. */
export const PARAMETER_RECORDS: readonly ParameterRecord[] = cloneAndDeepFreeze([
  // General coil geometry — D_i, D_o, D_m and D_c remain independent records.
  parameter({
    id: "coil.inner_diameter",
    symbol: "D_i",
    en: "Coil mechanical inner diameter",
    zh: "线圈机械内径",
    definition: "Diameter formed by the inner conductor surface; it is a mechanical boundary, not a current-path diameter.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    physicalRange: "D_i > 0",
    applicability: "Mechanical layout and insulation-gap geometry.",
    consumingMethods: ["B-01", "J-05"],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.outer_diameter",
    symbol: "D_o",
    en: "Coil mechanical outer diameter",
    zh: "线圈机械外径",
    definition: "Diameter formed by the outer conductor surface.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    physicalRange: "D_o > D_i",
    applicability: "Mechanical layout and 3D envelope.",
    consumingMethods: ["B-01"],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.mean_diameter",
    symbol: "D_m",
    en: "Coil geometric centerline diameter",
    zh: "线圈几何中心线直径",
    definition: "Mechanical diameter of the conductor geometric centerline; distinct from the electromagnetic current path.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    requirement: "derived_when_inputs_available",
    physicalRange: "D_i < D_m < D_o",
    applicability: "Uniform single-layer geometry and mechanical conductor-path length.",
    consumingMethods: ["B-01", "D-01"],
    aliases: [alias("Dmean", "Legacy import rename only."), alias("D_mean", "Legacy import rename only.")],
    default: controlledDefault(
      ["coil.inner_diameter", "coil.outer_diameter"],
      "B-01",
      [ADR_0003_REF],
    ),
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.current_path_diameter",
    symbol: "D_c",
    en: "Coil effective current-path diameter",
    zh: "线圈实际/等效电流路径直径",
    definition: "Actual or effective electromagnetic current-path diameter; it must not overwrite mechanical D_m.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    physicalRange: "D_c > 0",
    applicability: "Method- and state-bound electromagnetic geometry.",
    consumingMethods: ["B-01", "B-03", "B-04", "B-05", "C-01"],
    aliases: [
      alias(
        "coil.current_path_radius",
        "May only create a method-local radius after unit validation; never persist a second runtime geometry field.",
        "method_local_derivation",
      ),
    ],
    default: controlledDefault(
      ["coil.mean_diameter"],
      "B-01",
      [ADR_0003_REF],
      ["COIL_CURRENT_CENTROID_UNRESOLVED"],
    ),
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "conductor.radial_size",
    symbol: "d_rad",
    en: "Conductor radial section size",
    zh: "导体径向截面尺寸",
    definition: "Conductor outside dimension along the coil radial direction; it is not a coil diameter.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "d_rad > 0",
    applicability: "Installed conductor-section orientation must be known.",
    consumingMethods: ["B-01", "C-01"],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "conductor.axial_size",
    symbol: "d_ax",
    en: "Conductor axial section size",
    zh: "导体轴向截面尺寸",
    definition: "Conductor outside dimension along the coil axis.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "d_ax > 0",
    applicability: "Installed conductor-section orientation must be known.",
    consumingMethods: ["B-01", "B-02", "C-01"],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.pitch_center",
    symbol: "p",
    en: "Turn center-to-center pitch",
    zh: "相邻匝中心线轴向节距",
    definition: "Axial centerline pitch between adjacent turns; not applicable when N=1.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "p > 0 when N >= 2; not_applicable when N = 1",
    applicability: "Uniform single-layer winding.",
    consumingMethods: ["B-01", "C-01"],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.turn_clearance_axial",
    symbol: "g",
    en: "Axial turn clearance",
    zh: "匝间轴向净间隙",
    definition: "Net axial clearance between adjacent turns; never the radial insulation-to-coil gap.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "derived",
    requirement: "derived_when_inputs_available",
    physicalRange: "g >= 0 when N >= 2; not_applicable when N = 1",
    applicability: "Uniform single-layer winding.",
    consumingMethods: ["B-01"],
    aliases: [alias("g_turn", "Legacy display/import alias only.")],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.first_last_center_span",
    symbol: "b_cc",
    en: "First-to-last turn center span",
    zh: "首末匝中心线距离",
    definition: "Axial distance between first and last turn centerlines; not interchangeable with winding envelope length.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "derived",
    requirement: "derived_when_inputs_available",
    physicalRange: "b_cc >= 0",
    applicability: "Uniform single-layer winding; b_cc=0 for N=1.",
    consumingMethods: ["B-01"],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.winding_envelope_length",
    symbol: "b_env",
    en: "Winding axial envelope length",
    zh: "绕组完整轴向外包络长度",
    definition: "Full axial outside envelope of the winding; not Np, b_cc, or helix endpoint advance.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    requirement: "derived_when_inputs_available",
    physicalRange: "b_env > 0",
    applicability: "Mechanical/3D envelope and the frozen B-03/B-04/B-05 axial mapping.",
    consumingMethods: ["B-01", "B-02", "B-03", "B-04", "B-05", "C-01"],
    aliases: [
      alias("coil.sheet_length", "Only the frozen B-03/B-04 import mapping may rename this field."),
      alias("coil.winding_length", "Only the frozen B-05 import mapping may rename this field."),
    ],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.electrical_turn_count",
    symbol: "N",
    en: "Electrical turn count",
    zh: "电气匝数",
    definition: "Total electrical turns; a positive integer and independent of helix revolution count.",
    ownerModule: "B",
    dimension: "dimensionless",
    canonicalUnit: "one",
    physicalRange: "integer N >= 1",
    applicability: "Electrical winding methods; it must not silently define N_rev.",
    consumingMethods: ["B-01", "B-02", "B-03", "B-04", "B-05", "B-06", "C-01"],
    aliases: [alias("coil.turn_count", "Rename only; conflicting old/new values must be rejected.")],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.helix_revolution_count",
    symbol: "N_rev",
    en: "Helix revolution count",
    zh: "螺旋导体路径转数",
    definition: "Actual number of revolutions of the conductor center path; partial revolutions are allowed.",
    ownerModule: "B",
    dimension: "dimensionless",
    canonicalUnit: "one",
    physicalRange: "N_rev > 0",
    applicability: "Mechanical helix path; it is never inferred silently from N.",
    consumingMethods: ["B-01", "D-01"],
    aliases: [
      alias("coil.revolution_count", "Rename only; do not derive from electrical turns."),
      alias("Nrev", "Rename only; do not derive from electrical turns."),
    ],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.helix_axial_advance",
    symbol: "delta_z_helix",
    en: "Helix endpoint axial advance",
    zh: "螺旋路径轴向前进量",
    definition: "Signed axial advance from the start to end of the modeled helical center path.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "finite; sign follows the declared axis direction",
    applicability: "Mechanical helix path.",
    consumingMethods: ["B-01", "D-01"],
    aliases: [
      alias("Delta z", "Rename only after explicit unit validation."),
      alias("Δz", "Rename only after explicit unit validation."),
    ],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.lead_length",
    symbol: "lead_length",
    en: "Effective lead/busbar length",
    zh: "引线/母排有效长度",
    definition: "Effective conductor center-path length outside the active winding envelope.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "lead_length >= 0",
    applicability: "Complete conductor and terminal boundaries; missing leads permit only a lower bound.",
    consumingMethods: ["B-01", "D-01"],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "coil.turn_center_z[]",
    symbol: "z_i",
    en: "Turn-center axial coordinates",
    zh: "离散匝中心轴向坐标数组",
    definition: "Ordered turn-center axial coordinates in a declared coordinate system.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "finite coordinate array with fixed ordering and coordinate system",
    applicability: "Discrete-turn geometry and B-07.",
    consumingMethods: ["B-01", "B-07", "C-01"],
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),

  // Independent Wheeler B-06 multilayer geometry.
  parameter({
    id: "coil.multilayer_mean_radius",
    symbol: "a_ml",
    en: "Multilayer winding mean radius",
    zh: "多层绕组机械平均半径",
    definition: "Mechanical mean radius of the complete multilayer winding cross-section; not D_c/2 or a single-layer radius.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "a_ml > 0",
    applicability: "B-06 genuine multilayer geometry only.",
    consumingMethods: ["B-06"],
    aliases: [alias("coil.mean_radius", "B-06 import mapping only; never map to D_c/2.")],
  }),
  parameter({
    id: "coil.multilayer_axial_length",
    symbol: "b_ml",
    en: "Multilayer winding axial length",
    zh: "多层绕组完整轴向长度",
    definition: "Full axial length of the complete multilayer winding cross-section.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "b_ml > 0",
    applicability: "B-06 genuine multilayer geometry only.",
    consumingMethods: ["B-06"],
    aliases: [alias("coil.axial_length", "B-06 import mapping only.")],
  }),
  parameter({
    id: "coil.multilayer_radial_build",
    symbol: "c_ml",
    en: "Multilayer winding radial build",
    zh: "多层绕组合计径向厚度",
    definition: "Total radial build of all winding layers; never a single conductor radial size.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "c_ml > 0",
    applicability: "B-06 genuine multilayer geometry only.",
    consumingMethods: ["B-06"],
    aliases: [alias("coil.radial_build", "B-06 import mapping only; legacy symbol t remains provenance only.")],
  }),
  parameter({
    id: "coil.layer_count",
    symbol: "N_layer",
    en: "Winding layer count",
    zh: "绕组层数",
    definition: "Integer count of physical winding layers used to prove that B-06 geometry is genuinely multilayer.",
    ownerModule: "B",
    dimension: "dimensionless",
    canonicalUnit: "one",
    physicalRange: "integer N_layer >= 2 for B-06",
    applicability: "B-06 genuine multilayer routing.",
    consumingMethods: ["B-06"],
  }),

  // Workpiece, insulation and radial-gap geometry.
  parameter({
    id: "workpiece.outer_diameter",
    symbol: "D_w,o",
    en: "Workpiece outer diameter",
    zh: "工件外径",
    definition: "Outer diameter of the heated solid or furnace tube.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "D_w,o > 0",
    applicability: "Workpiece electromagnetic and thermal geometry.",
    consumingMethods: ["E-01", "E-03"],
  }),
  parameter({
    id: "workpiece.inner_diameter",
    symbol: "D_w,i",
    en: "Workpiece inner diameter",
    zh: "空心工件内径",
    definition: "Inner diameter of a hollow workpiece; a solid-state zero must be explicit and missing must not masquerade as zero.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "0 <= D_w,i < D_w,o when applicable",
    applicability: "Hollow workpieces; solid workpieces use explicit zero or not_applicable state.",
    consumingMethods: ["E-01"],
  }),
  parameter({
    id: "workpiece.active_length",
    symbol: "L_w,act",
    en: "Workpiece active length",
    zh: "工件轴向有效长度",
    definition: "Axial workpiece length inside the current electromagnetic or thermal control volume.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "L_w,act > 0",
    applicability: "Any workpiece control-volume calculation that declares an active length.",
  }),
  parameter({
    id: "insulation.inner_diameter",
    symbol: "D_ins,i",
    en: "Insulation inner diameter",
    zh: "保温层内径",
    definition: "Diameter of the insulation inner surface.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "D_ins,i > 0",
    applicability: "Cylindrical insulation geometry.",
    consumingMethods: ["J-01", "I-01", "I-02", "I-03", "I-04"],
  }),
  parameter({
    id: "insulation.outer_diameter",
    symbol: "D_ins,o",
    en: "Insulation outer diameter",
    zh: "保温层外径",
    definition: "Diameter of the insulation outer surface and inner boundary of the coil-insulation annulus.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "D_ins,o > D_ins,i",
    applicability: "Cylindrical insulation and J-05 gap geometry.",
    consumingMethods: ["J-01", "J-05", "I-01", "I-02", "I-03", "I-04"],
  }),
  parameter({
    id: "thermal.radial_gap",
    symbol: "s_ann",
    en: "Single-sided radial annulus gap",
    zh: "线圈与保温层单边径向空气隙",
    definition: "Single-sided mechanical radial gap between the coil inner surface and insulation outer surface; never an unhalved diameter difference.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    requirement: "derived_when_inputs_available",
    physicalRange: "s_ann >= 0",
    applicability: "Coil-insulation annulus; direct measurement requires mapping ID and uncertainty.",
    consumingMethods: ["J-05"],
    aliases: [alias("g_rad", "Legacy import alias only; canonical symbol is s_ann and it is unrelated to turn clearance g.")],
    default: controlledDefault(
      ["coil.inner_diameter", "insulation.outer_diameter"],
      "J-05",
      [ADR_0003_REF],
    ),
    definitionSourceRefs: [PARAMETER_DICTIONARY_REF, ADR_0003_REF],
  }),
  parameter({
    id: "thermal.effective_length",
    symbol: "L_th",
    en: "Thermal sidewall effective length",
    zh: "侧壁传热有效长度",
    definition: "Axial length covered by the current sidewall heat-transfer model; end losses are separate.",
    ownerModule: "J",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "L_th > 0",
    applicability: "Cylindrical sidewall thermal methods with explicit end treatment.",
    consumingMethods: ["J-01", "J-02", "J-03", "J-05", "J-06", "I-01", "I-02", "I-03"],
  }),
  parameter({
    id: "thermal.orientation",
    symbol: "—",
    en: "Thermal geometry orientation",
    zh: "热工几何方向",
    definition: "Controlled orientation: horizontal_axis, vertical_axis, or inclined.",
    ownerModule: "J",
    dimension: "dimensionless",
    canonicalUnit: "one",
    physicalRange: "horizontal_axis | vertical_axis | inclined",
    applicability: "Convection and annulus correlation routing.",
    consumingMethods: ["J-02", "J-05"],
  }),
  parameter({
    id: "thermal.gap_boundary",
    symbol: "—",
    en: "Annulus boundary classification",
    zh: "环隙边界类型",
    definition: "Controlled gap boundary: sealed_continuous, sealed_near_concentric, open_top_bottom, discrete_helix_open, or complex_3d.",
    ownerModule: "J",
    dimension: "dimensionless",
    canonicalUnit: "one",
    physicalRange: "registered thermal.gap_boundary enum",
    applicability: "J-05 classification and fail-closed routing.",
    consumingMethods: ["J-05"],
  }),

  // Conductor and coolant-passage geometry.
  parameter({
    id: "conductor.shape",
    symbol: "—",
    en: "Conductor cross-section shape",
    zh: "导体截面形状",
    definition: "Controlled shape: solid_round, hollow_round, solid_rectangular, hollow_rectangular, or custom.",
    ownerModule: "B",
    dimension: "dimensionless",
    canonicalUnit: "one",
    physicalRange: "registered conductor.shape enum",
    applicability: "Conductor, AC-resistance and cooling-passage geometry routing.",
    consumingMethods: ["D-02", "D-05"],
  }),
  parameter({
    id: "conductor.outer_diameter",
    symbol: "d_o",
    en: "Round conductor outer diameter",
    zh: "圆导体外径",
    definition: "Outer diameter of a round conductor cross-section; it is not coil D_o.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "d_o > 0",
    applicability: "Round conductor geometry.",
    consumingMethods: ["D-02", "D-05"],
  }),
  parameter({
    id: "conductor.inner_diameter",
    symbol: "d_i",
    en: "Round conductor coolant-hole diameter",
    zh: "圆管导体内径",
    definition: "Inner diameter of a hollow round conductor; not_applicable for a solid conductor.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    physicalRange: "0 < d_i < d_o for hollow_round; not_applicable for solid_round",
    applicability: "Hollow round conductor geometry.",
    consumingMethods: ["D-02", "D-05"],
  }),
  parameter({
    id: "conductor.wall_thickness",
    symbol: "t_wall",
    en: "Conductor wall thickness",
    zh: "圆管导体壁厚",
    definition: "Wall thickness of a round hollow conductor, kept distinct from skin depth and winding radial build.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    physicalRange: "t_wall > 0 and consistent with outer/inner conductor diameters",
    applicability: "Hollow conductor geometry and D-05 applicability screening.",
    consumingMethods: ["D-02", "D-05"],
  }),
  parameter({
    id: "conductor.metal_area",
    symbol: "A_metal",
    en: "Conducting metal area",
    zh: "导体金属截面积",
    definition: "True metal cross-sectional area available for conduction; never coolant flow area.",
    ownerModule: "B",
    dimension: "area",
    canonicalUnit: "m2",
    role: "input_or_derived",
    physicalRange: "A_metal > 0",
    applicability: "Resistance, current-density and conductor mass calculations.",
    consumingMethods: ["D-03", "D-06"],
  }),
  parameter({
    id: "coolant.flow_area",
    symbol: "A_flow",
    en: "Coolant flow area",
    zh: "冷却流道面积",
    definition: "Internal coolant flow area; never conducting metal area.",
    ownerModule: "B",
    dimension: "area",
    canonicalUnit: "m2",
    role: "input_or_derived",
    physicalRange: "A_flow > 0",
    applicability: "Supported internal coolant passage geometry.",
    consumingMethods: ["D-02", "H-03"],
  }),
  parameter({
    id: "coolant.wetted_perimeter",
    symbol: "P_wetted",
    en: "Coolant wetted perimeter",
    zh: "冷却流道润湿周长",
    definition: "Perimeter in contact with coolant used for hydraulic diameter.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    physicalRange: "P_wetted > 0",
    applicability: "Supported internal coolant passage geometry.",
    consumingMethods: ["D-02", "H-03"],
  }),
  parameter({
    id: "coolant.hydraulic_diameter",
    symbol: "D_h",
    en: "Coolant hydraulic diameter",
    zh: "冷却流道水力直径",
    definition: "Hydraulic diameter derived from the actual flow area and wetted perimeter.",
    ownerModule: "B",
    dimension: "length",
    canonicalUnit: "m",
    role: "input_or_derived",
    physicalRange: "D_h > 0",
    applicability: "Internal-flow correlations whose geometry assumptions match the passage.",
    consumingMethods: ["H-03", "H-04", "H-05"],
  }),
  parameter({
    id: "coolant.branch_count",
    symbol: "N_branch",
    en: "Parallel coolant branch count",
    zh: "冷却并联支路数",
    definition: "Number of parallel coolant branches; it never implies equal flow division by itself.",
    ownerModule: "B",
    dimension: "dimensionless",
    canonicalUnit: "one",
    physicalRange: "integer N_branch >= 1",
    applicability: "Cooling network topology with explicit branch geometry/resistance.",
    consumingMethods: ["H-03", "H-05"],
  }),

  // Electromagnetic state and electrical ports.
  parameter({
    id: "frequency",
    symbol: "f",
    en: "Fundamental frequency",
    zh: "基本频率",
    definition: "Fundamental sinusoidal frequency; angular frequency is a method-local derived quantity.",
    ownerModule: "K",
    dimension: "frequency",
    canonicalUnit: "Hz",
    role: "state",
    physicalRange: "f > 0",
    applicability: "All frequency-domain electromagnetic and circuit methods.",
    consumingMethods: ["D-04", "D-05", "D-07", "E-01", "E-02", "E-03", "F-01", "F-02", "G-07", "G-08", "G-09"],
  }),
  parameter({
    id: "resistivity",
    symbol: "rho_e",
    en: "Electrical resistivity",
    zh: "电阻率",
    definition: "State-bound electrical resistivity in canonical SI; an unconverted ohm-centimetre value is invalid.",
    ownerModule: "A",
    dimension: "electrical_resistivity",
    canonicalUnit: "ohm_m",
    role: "state",
    physicalRange: "rho_e > 0",
    applicability: "Material, temperature, field and frequency state must match the consuming method.",
    consumingMethods: ["D-03", "D-04", "D-05", "E-01", "E-02", "E-03"],
  }),
  parameter({
    id: "relative_permeability",
    symbol: "mu_r",
    en: "Effective relative permeability",
    zh: "有效相对磁导率",
    definition: "Effective relative permeability bound to temperature, field/flux, frequency and material state.",
    ownerModule: "A",
    dimension: "dimensionless",
    canonicalUnit: "one",
    role: "state",
    physicalRange: "mu_r > 0",
    applicability: "Only inside the material data domain for T, H/B, f and phase/state.",
    consumingMethods: ["B-03", "D-04", "E-01", "E-02", "E-03"],
  }),
  parameter({
    id: "skin_depth",
    symbol: "delta",
    en: "Electromagnetic skin depth",
    zh: "电磁趋肤/透入深度",
    definition: "Reference 1/e electromagnetic field-amplitude depth; it is not a thermal affected depth.",
    ownerModule: "E",
    dimension: "length",
    canonicalUnit: "m",
    role: "derived",
    requirement: "derived_when_inputs_available",
    physicalRange: "delta > 0",
    applicability: "Linear, uniform, good-conductor sinusoidal reference models only.",
    consumingMethods: ["D-05", "E-02", "E-03"],
  }),
  parameter({
    id: "port.impedance",
    symbol: "Z",
    en: "Port complex impedance",
    zh: "端口复阻抗",
    definition: "Complex impedance at a specified port, frequency, quantity basis and loaded state.",
    ownerModule: "F",
    dimension: "electrical_resistance",
    canonicalUnit: "ohm",
    role: "input_or_derived",
    physicalRange: "finite complex impedance with declared passive-sign convention",
    applicability: "Explicit port, RMS/fundamental basis and loaded state required.",
    consumingMethods: ["F-02", "G-07", "G-08", "G-09", "G-10"],
  }),
  parameter({
    id: "port.req_series",
    symbol: "R_eq",
    en: "Series-equivalent port resistance",
    zh: "端口串联等效实部",
    definition: "Real part of the same-state series-equivalent port impedance.",
    ownerModule: "F",
    dimension: "electrical_resistance",
    canonicalUnit: "ohm",
    role: "input_or_derived",
    physicalRange: "R_eq >= 0 for a passive identified/modelled port",
    applicability: "Same port, frequency, state and de-embedding boundary as its companion impedance.",
    consumingMethods: ["D-07", "F-01", "G-07", "G-08", "G-09", "G-10"],
  }),
  parameter({
    id: "port.leq_series",
    symbol: "L_eq",
    en: "Series-equivalent port inductance",
    zh: "端口串联等效电感",
    definition: "Inductive series equivalent derived from port reactance; a capacitive state must not be labelled inductance.",
    ownerModule: "F",
    dimension: "inductance",
    canonicalUnit: "H",
    role: "input_or_derived",
    physicalRange: "L_eq >= 0 only for a verified inductive state",
    applicability: "Explicit same-state frequency and reactance sign required.",
    consumingMethods: ["D-07", "F-01", "G-07", "G-08", "G-09", "G-10"],
  }),
  parameter({
    id: "port.voltage_rms",
    symbol: "V_rms",
    en: "Port RMS voltage",
    zh: "端口 RMS 电压",
    definition: "RMS phasor or magnitude at a specified port and frequency.",
    ownerModule: "F",
    dimension: "voltage",
    canonicalUnit: "V",
    role: "input_or_derived",
    physicalRange: "V_rms >= 0",
    applicability: "Port and fundamental/full-wave basis must be explicit.",
    consumingMethods: ["F-02", "G-06", "G-07", "G-08", "G-09", "G-10"],
  }),
  parameter({
    id: "port.current_rms",
    symbol: "I_rms",
    en: "Port RMS current",
    zh: "端口 RMS 电流",
    definition: "RMS phasor or magnitude at a specified port and frequency.",
    ownerModule: "F",
    dimension: "electric_current",
    canonicalUnit: "A",
    role: "input_or_derived",
    physicalRange: "I_rms >= 0",
    applicability: "Port and fundamental/full-wave basis must be explicit.",
    consumingMethods: ["D-06", "D-07", "F-02", "G-06", "G-07", "G-08", "G-09", "G-10"],
  }),
  parameter({
    id: "port.active_power",
    symbol: "P",
    en: "Port active power",
    zh: "端口有功功率",
    definition: "Active power absorbed at the same port and time basis under the frozen passive-sign convention.",
    ownerModule: "F",
    dimension: "power",
    canonicalUnit: "W",
    role: "input_or_derived",
    physicalRange: "P >= 0 for a passive receiving port, within measurement uncertainty",
    applicability: "Same port, time window and RMS/full-wave basis as V and I.",
    consumingMethods: ["F-02", "G-04", "G-06"],
  }),
  parameter({
    id: "port.reactive_power",
    symbol: "Q",
    en: "Port reactive power",
    zh: "端口无功功率",
    definition: "Reactive power at the stated port; sign follows the frozen RMS phasor convention.",
    ownerModule: "F",
    dimension: "power",
    canonicalUnit: "W",
    allowedDisplayUnits: POWER_DISPLAY_UNIT_FAMILIES.reactive,
    role: "input_or_derived",
    physicalRange: "finite signed reactive power",
    applicability: "Same port, time window and phasor convention as V and I.",
    consumingMethods: ["F-02", "G-06"],
  }),

  // Distinct power and heat-flow control-volume quantities.
  ...[
    ["P_grid", "P_grid", "Grid input active power", "网侧输入有功功率", "G", ["G-04", "G-05"]],
    ["P_inverter_out", "P_inverter_out", "Inverter output active power", "逆变器输出有功功率", "G", ["G-04", "G-05"]],
    ["P_coil_terminal", "P_coil_terminal", "Coil-terminal active power", "线圈端有功功率", "G", ["G-04", "G-05"]],
    ["P_workpiece_absorbed", "P_workpiece_absorbed", "Workpiece absorbed power", "工件吸收功率", "G", ["G-03", "G-04", "G-05"]],
    ["P_useful", "P_useful", "Useful process power", "工艺有用功率", "G", ["G-03", "G-04", "G-05"]],
    ["P_cu", "P_cu", "Coil copper loss", "线圈铜损", "D", ["G-04", "G-05", "H-01"]],
    ["Q_loss_environment", "Q_loss_environment", "Heat loss to environment", "向环境热损", "J", ["G-03", "G-04", "G-05"]],
    ["Q_pickup_to_coil", "Q_pickup_to_coil", "External heat picked up by coil", "外部进入线圈的热拾取", "H", ["H-01"]],
    ["Q_coolant", "Q_coolant", "Heat entering specified coolant circuit", "指定水路冷却热负荷", "H", ["H-02", "H-07"]],
    ["P_other_cooled", "P_other_cooled", "Other explicit water-cooled heat load", "其他明确水冷负荷", "H", ["H-01"]],
  ].map(([id, symbol, en, zh, ownerModule, consumingMethods]) =>
    parameter({
      id: id as string,
      symbol: symbol as string,
      en: en as string,
      zh: zh as string,
      definition: `${en as string}; a distinct control-volume quantity that must not be exchanged with another power boundary.`,
      ownerModule: ownerModule as EngineeringModuleId,
      dimension: "power",
      canonicalUnit: "W",
      role: "input_or_derived",
      physicalRange: "value >= 0 on its declared control-volume and time basis",
      applicability: "Only the explicitly named control volume; unknown terms remain missing rather than zero.",
      consumingMethods: consumingMethods as readonly string[],
    }),
  ),

  // Temperature and fluid quantities explicitly separated by the dictionary.
  parameter({
    id: "water.pressure_abs",
    symbol: "p_abs",
    en: "Water absolute pressure",
    zh: "水绝对压力",
    definition: "Absolute water pressure; gauge pressure must be converted at the boundary with provenance.",
    ownerModule: "H",
    dimension: "pressure",
    canonicalUnit: "Pa",
    role: "state",
    physicalRange: "p_abs > 0",
    applicability: "Water properties, local saturation and pressure-loss calculations.",
    consumingMethods: ["A-02", "H-02", "H-05", "H-06", "H-07"],
  }),
  parameter({
    id: "water.mass_flow",
    symbol: "m_dot",
    en: "Water mass flow rate",
    zh: "水质量流量",
    definition: "Mass flow rate through the declared coolant control volume or branch.",
    ownerModule: "H",
    dimension: "mass_flow_rate",
    canonicalUnit: "kg_per_s",
    role: "input_or_derived",
    physicalRange: "m_dot >= 0; positive for an operating branch",
    applicability: "Explicit loop/branch and time basis required.",
    consumingMethods: ["H-02", "H-06", "H-07"],
  }),
  parameter({
    id: "water.volume_flow",
    symbol: "V_dot",
    en: "Water volume flow rate",
    zh: "水体积流量",
    definition: "Volumetric flow rate at the stated thermodynamic state; never stored in the mass-flow or velocity field.",
    ownerModule: "H",
    dimension: "volume_flow_rate",
    canonicalUnit: "m3_per_s",
    role: "input_or_derived",
    physicalRange: "V_dot >= 0",
    applicability: "Explicit loop/branch and density state required.",
    consumingMethods: ["H-02", "H-03"],
  }),
  parameter({
    id: "water.velocity",
    symbol: "v",
    en: "Mean water velocity",
    zh: "水平均流速",
    definition: "Mean branch velocity based on the actual branch volume flow and flow area.",
    ownerModule: "H",
    dimension: "velocity",
    canonicalUnit: "m_per_s",
    role: "derived",
    physicalRange: "v >= 0",
    applicability: "A declared branch and supported flow-passage geometry.",
    consumingMethods: ["H-04", "H-05"],
  }),
  parameter({
    id: "water.bulk_temperature",
    symbol: "T_bulk",
    en: "Water bulk temperature",
    zh: "水体平均温度",
    definition: "Bulk coolant temperature, kept separate from local inner-wall and outer-wall temperatures.",
    ownerModule: "H",
    dimension: "absolute_temperature",
    canonicalUnit: "K",
    role: "state",
    physicalRange: "T_bulk > 0 K",
    applicability: "State-bound water properties and cooling calculations.",
    consumingMethods: ["A-02", "H-02", "H-04", "H-06", "H-07"],
  }),
  parameter({
    id: "tube.inner_wall_temperature",
    symbol: "T_wall,inner",
    en: "Tube inner-wall temperature",
    zh: "管内壁温度",
    definition: "Estimated or measured coolant-side tube wall temperature at a declared local position.",
    ownerModule: "H",
    dimension: "absolute_temperature",
    canonicalUnit: "K",
    role: "input_or_derived",
    physicalRange: "T_wall,inner > 0 K",
    applicability: "Local boiling/saturation screening with matching pressure and heat flux.",
    consumingMethods: ["H-06"],
  }),
  parameter({
    id: "tube.outer_wall_temperature",
    symbol: "T_wall,outer",
    en: "Tube outer-wall temperature",
    zh: "管外壁温度",
    definition: "Estimated or measured external tube-wall temperature at a declared local position.",
    ownerModule: "H",
    dimension: "absolute_temperature",
    canonicalUnit: "K",
    role: "input_or_derived",
    physicalRange: "T_wall,outer > 0 K",
    applicability: "Coil thermal boundary and external heat-pickup calculations.",
    consumingMethods: ["H-01", "H-06", "J-05"],
  }),
  parameter({
    id: "coil.mean_temperature",
    symbol: "T_coil,mean",
    en: "Coil mean temperature",
    zh: "线圈平均温度",
    definition: "Mean coil material temperature for state-dependent conductor properties; not a local hot-spot temperature.",
    ownerModule: "D",
    dimension: "absolute_temperature",
    canonicalUnit: "K",
    role: "state",
    physicalRange: "T_coil,mean > 0 K",
    applicability: "Coil material property and resistance state.",
    consumingMethods: ["A-01", "D-03", "D-04", "D-05", "D-06"],
  }),
  parameter({
    id: "saturation_margin_wall",
    symbol: "DeltaT_sat,wall",
    en: "Wall saturation-temperature margin",
    zh: "壁面饱和温差裕量",
    definition: "Thermodynamic temperature difference between local saturation temperature and estimated inner-wall temperature; a positive value is not by itself a no-boiling safety proof.",
    ownerModule: "H",
    dimension: "temperature_difference",
    canonicalUnit: "K",
    role: "derived",
    requirement: "derived_when_inputs_available",
    physicalRange: "finite signed temperature difference",
    applicability: "Local absolute pressure and inner-wall temperature must be available.",
    consumingMethods: ["H-06"],
  }),
]);

export const PARAMETER_REGISTRY = new ParameterRegistry(PARAMETER_RECORDS);
